name: 'yt2anchorfm'
author: 'Guilherme Costa'
description: 'yt2anchorfm helps you to upload an audio file from a given youtube video automatically to your Anchor.fm account.'
runs:
  using: 'composite'
  steps:
    - name: Cloning yt2anchorfm repo
      uses: actions/checkout@v2
      with:
        repository: zephyrus3/yt2anchorfm
        path: yt2anchorfm

    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2

    - name: Check geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
      shell: bash

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y ffmpeg
      shell: bash

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r yt2anchorfm/requirements.txt
      shell: bash

    - name: Run yt2anchor.py
      run: |
        python yt2anchorfm/yt2anchor.py
      env:
        ANCHOR_EMAIL: ${{inputs.ANCHOR_EMAIL}}
        ANCHOR_PASSWORD: ${{inputs.ANCHOR_PASSWORD}}
        EPISODE_PATH: ${{inputs.EPISODE_PATH}}
        KEEP_EPISODES_NUM: ${{inputs.KEEP_EPISODES_NUM}}
      shell: bash

inputs:
 ANCHOR_EMAIL:
    description: 'Email used to log in to Anchor.fm'
    required: true
 ANCHOR_PASSWORD:
    description: 'Password used to log in to Anchor.fm'
    required: true
 EPISODE_PATH:
    description: "Path used inside the container environment that points to the cloned repo. Usually you don't want to change this."
    required: false
    default: '${{ github.workspace }}'
 KEEP_EPISODES_NUM:
    description: 'Number of latest episodes to keep after an upload. Drafts and older episodes will be deleted. Using zero will not remove any episodes.'
    required: false
    default: '0'

branding:
  icon: 'upload-cloud'
  color: 'purple'
