name: 'yt2anchorfm'
author: 'Guilherme Costa'
description: 'yt2anchorfm helps you to upload an audio file from a given youtube video automatically to your Anchor.fm account.'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.2

    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y ffmpeg

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run yt2anchor.py
      run: |
        python yt2anchor.py
      with:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: ${{ github.workspace }}

inputs:
 ANCHOR_EMAIL:
    description: 'Email used to logging on Anchor.fm'
    required: true
 ANCHOR_PASSWORD:
    description: 'Password used to logging on Anchor.fm'
    required: true
 EPISODE_PATH:
    description: 'Path used inside docker environment that points to the cloned repo'
    required: false
    default: '${{ github.workspace }}'
 KEEP_EPISODES_NUM:
    description: 'Number of episodes to keep after an upload'
    required: false
    default: '0'

branding:
  icon: 'upload-cloud'
  color: 'purple'
