version: '3'

services:
  yt2anchor:
    image: yt2anchor:ubuntu
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    env_file:
      - ./.env
    volumes:
      - ./episode.json:/data/episode.json
