version: '3'

services:
  yt2anchor:
    image: yt2anchor:alpine
    build:
      context: .
      dockerfile: docker/Dockerfile.alpine
    env_file:
      - ./.env
    volumes:
      - ./episode.json:/data/episode.json
