name: 'yt2anchor - Upload Episode'
on:
  push:
    paths:
      - episode.json
    branches: [main]
jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Episode from YouTube To Anchor.Fm
        uses: zephyrus3/yt2anchorfm@main
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: ${{ secrets.EPISODE_PATH }}
          KEEP_EPISODES_NUM: 2
